---
title: "Mighty "Nein""
output: pdf_document
---

```{r}
library(tidyr)
library(tidytext)
library(tidyverse)
library(readtext)
library(rvest)
library(ggplot2)
library(plyr)
library(viridis)
library(hrbrthemes)
library(magrittr)

```


```{r setup, include=FALSE}

## try with just one episode before automating all transcript scrapings
# this takes about 5 minutes
episode1 <- read_lines('https://criticalrole.fandom.com/wiki/Curious_Beginnings/Transcript') %>% 
  data_frame(text = .) %>%
  unnest_tokens(word, text, format = "html")

# this figure isn't the main objective, but it's super cute that the main words used in 
# episode one are all of the actors names. 
episode1  %>%
  dplyr::count(word, sort = T) %>% #need dplyr:: to differentiate from plyr::count
  filter(n > 50) %>%
  anti_join(stop_words) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col(fill = "purple") +
  xlab(NULL) +
  coord_flip() +
  theme_bw() +
  labs(y = "Word Frequencies for Oliver Twist")
```


```{r obtain episode names }

  
  url <- "https://criticalrole.fandom.com/wiki/List_of_episodes"
page <- read_html(url)

  table <- list()
  
# Episode names and details are contained in several different tables, separated by story arcs. 
#  Tables numbers were manually acquired for just the second campaign
# Useful resource for finding xpath details: https://www.r-bloggers.com/2015/01/using-rvest-to-scrape-an-html-table/
  
  for(tab.num in 6:14){ 
     temp <- page %>% 
  html_nodes(xpath = paste0('//*[@id="mw-content-text"]/div/table[', tab.num, ']')) %>%
  html_table()

       table[[tab.num-5]] <- temp[[1]]
  }

  table.1 <- table[[1]]

episode.details <- table %>%
  reduce(full_join)  

##obtain just text name - between ""
# reference: https://stackoverflow.com/questions/32320081/how-to-extract-text-between-quotations-in-r

episode.names <- sub('.*"(.*)".*', "\\1", episode.details$Title)

#replace " " with "_" to match website style
#reference: https://stackoverflow.com/questions/53107014/replace-space-between-two-words-with-an-underscore-in-a-vector

ep.names_ <- gsub(" ", "_", episode.names)

#fix oddly named episodes that don't match websites
ep.names_[36] <- "O_Captain,_Who%27s_Captain%3F"
ep.names_[51] <- "Xhorhas_(episode)" 
```

```{r}
## obtain transcripts from all 141 episodes in Critical Role Campaign 2: The Mighty Nein
# all.episodes <- list()
# 
# #this will take several hours to run, Rdata file for first 107 episodes included
# for(ep in 1:length(ep.names_)){
#   all.episodes[[ep]] <- read_lines(paste0('https://criticalrole.fandom.com/wiki/', 
# ep.names_[ep],
# '/Transcript')) %>% 
#   data_frame(text = .) %>%
#   unnest_tokens(word, text, format = "html")
# }
# 
# 
# save(all.episodes, file = "./all.ep.transcripts107.Rdata")

## already obtained transcripts
load("all.ep.transcripts107.Rdata")

```


```{r}
#word count for "nein" for each episode
nein.count <- data.frame(matrix(data = NA, nrow = length(all.episodes), ncol = 2))
colnames(nein.count) <-  c("count", "ep.num")

for(ep in 1:length(all.episodes)){
 temp <-all.episodes[[ep]]  %>%
  dplyr::count(word, sort = TRUE) %>%
  filter(word == "nein")

 nein.count[ep,] <- c(pull(temp[, 2]), ep)
}

# x and y position from episode number 

nein.count$x <- c(rep(1:10, 10), 1:7)
nein.count$y <- c(rep(1:10, each = 10), rep(11, 7))

```

```{r}
## gridded heatmap for use of "nein" by episode
nein.plot <- ggplot(nein.count, aes(x, y, fill= count)) + 
  geom_tile()+
  scale_fill_viridis(discrete=F, "Use Count") +
  geom_text(aes(label = ep.num), col = "white") +
  theme(axis.text.x=element_blank(), 
        axis.text.y = element_blank(), 
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
         axis.ticks.x=element_blank(),
         axis.ticks.y=element_blank())  +
  labs(title = "Heatmap of 'Nein' Use in Each Episode",
              subtitle = "Critical Role: The Mighty Nein Campaign",
              caption = "Data source: https://criticalrole.fandom.com/wiki/Transcripts")

ggsave(filename = "./Figures/neinplot.png", limitsize = F,
      dpi = 300
      )

## add box around episode where they name themselves (ep 8)
```


